# Verify the Property Av=λv

In [1]:
import numpy as np

A = np.array([
    [4,2,1],
    [2,3,1],
    [1,1,2]
])


In [2]:
eigVal, eigVec = np.linalg.eig(A)

In [3]:
print(eigVal)
print(eigVec)

[6.04891734 1.64310413 1.30797853]
[[ 0.73697623  0.59100905  0.32798528]
 [ 0.59100905 -0.32798528 -0.73697623]
 [ 0.32798528 -0.73697623  0.59100905]]


In [4]:
lamda1 = eigVal[0]
print(lamda1)

6.0489173395223075


In [9]:
v = eigVec[:,0]
print(v)

[0.73697623 0.59100905 0.32798528]


In [11]:
left = A @ v
right = lamda1 * v

In [12]:
print(left)
print(right)

[4.45790829 3.57496488 1.98395583]
[4.45790829 3.57496488 1.98395583]


In [13]:
print(np.allclose(left, right))

True
