# Eigenvalues & Eigenvectors (Movie Recommendation System)

## Genre Relation ship matrix is A

In [1]:
import numpy as np

A = np.array([
    [4,2,1],
    [2,3,1],
    [1,1,2]
])

# Eigenvalues and Eigenvectors

In [2]:
eigVals, eigVec = np.linalg.eig(A)
print(eigVals)
print(eigVec)

[6.04891734 1.64310413 1.30797853]
[[ 0.73697623  0.59100905  0.32798528]
 [ 0.59100905 -0.32798528 -0.73697623]
 [ 0.32798528 -0.73697623  0.59100905]]
