# Determinant and Inverse 

In [2]:
import numpy as np


In [6]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)
print(type(matrix))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [4]:
det = np.linalg.det(matrix)
det

np.float64(-2.0000000000000004)

In [5]:
inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Eigen Values and Eigen Vectors

In [12]:
mat = np.array([[1, 2], [3, 4]])
print(mat)

[[1 2]
 [3 4]]


In [14]:
eigvals, eigvector= np.linalg.eig(mat)
print(eigvals)
print(eigvector)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Single Value Decomposition 