# Matrix Decomposition Methods (One Complete AI Case Study)

# LU

In [1]:
import numpy as np
from scipy.linalg import lu

In [3]:
A = np.array([
    [8, 2, 1],
    [2, 6, 1],
    [1, 1, 5]
], dtype=float)

In [4]:
print(A)

[[8. 2. 1.]
 [2. 6. 1.]
 [1. 1. 5.]]


In [7]:
P, lower, upper = lu(A)

In [8]:
print(P)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
lower

array([[1.        , 0.        , 0.        ],
       [0.25      , 1.        , 0.        ],
       [0.125     , 0.13636364, 1.        ]])

In [10]:
upper

array([[8.        , 2.        , 1.        ],
       [0.        , 5.5       , 0.75      ],
       [0.        , 0.        , 4.77272727]])

In [17]:
orig = P @ lower @ upper

In [18]:
orig

array([[8., 2., 1.],
       [2., 6., 1.],
       [1., 1., 5.]])

In [19]:
np.allclose(A, orig)

True

# QR Decomposition 

In [21]:
A = np.array([
    [2, 1],
    [3, 2],
    [4, 3],
    [5, 4]
], dtype=float)

In [22]:
A

array([[2., 1.],
       [3., 2.],
       [4., 3.],
       [5., 4.]])

In [23]:
Q, R = np.linalg.qr(A)

In [24]:
Q

array([[-0.27216553, -0.79115481],
       [-0.40824829, -0.36514837],
       [-0.54433105,  0.06085806],
       [-0.68041382,  0.4868645 ]])

In [25]:
R

array([[-7.34846923, -5.44331054],
       [ 0.        ,  0.60858062]])

In [26]:
Q @ R

array([[2., 1.],
       [3., 2.],
       [4., 3.],
       [5., 4.]])

In [27]:
np.allclose(A, Q @ R)

True

# Eigen Value Decomposition

In [29]:
A = np.array([
    [4, 2, 1],
    [2, 3, 1],
    [1, 1, 2]
], dtype=float)

In [30]:
A

array([[4., 2., 1.],
       [2., 3., 1.],
       [1., 1., 2.]])

In [31]:
eigenVals, eigenVec = np.linalg.eig(A) 

In [32]:
eigenVals

array([6.04891734, 1.64310413, 1.30797853])

In [33]:
eigenVec

array([[ 0.73697623,  0.59100905,  0.32798528],
       [ 0.59100905, -0.32798528, -0.73697623],
       [ 0.32798528, -0.73697623,  0.59100905]])

In [37]:
lambda1 = np.diag(eigenVals)
lambda1

array([[6.04891734, 0.        , 0.        ],
       [0.        , 1.64310413, 0.        ],
       [0.        , 0.        , 1.30797853]])

In [38]:
orig = eigenVec @ lambda1 @ np.linalg.inv(eigenVec)
orig

array([[4., 2., 1.],
       [2., 3., 1.],
       [1., 1., 2.]])

In [39]:
np.allclose(orig, A)

True

# Cholesky Decomposition :

In [41]:
A = np.array([
    [6, 2, 1],
    [2, 5, 2],
    [1, 2, 4]
], dtype=float)

In [42]:
A

array([[6., 2., 1.],
       [2., 5., 2.],
       [1., 2., 4.]])

In [46]:
L = np.linalg.cholesky(A)

In [47]:
L

array([[2.44948974, 0.        , 0.        ],
       [0.81649658, 2.081666  , 0.        ],
       [0.40824829, 0.80064077, 1.78670302]])

In [48]:
LT = L.T
LT

array([[2.44948974, 0.81649658, 0.40824829],
       [0.        , 2.081666  , 0.80064077],
       [0.        , 0.        , 1.78670302]])

In [49]:
orig = L @ LT
orig

array([[6., 2., 1.],
       [2., 5., 2.],
       [1., 2., 4.]])

In [50]:
np.allclose(A, orig)

True