# Verify the Property det(A−λI)=0

In [1]:
import numpy as np

A = np.array([
    [4,2,1],
    [2,3,1],
    [1,1,2]
])

In [2]:
eigVals, eigVec = np.linalg.eig(A)
print(eigVals)
print(eigVec)

[6.04891734 1.64310413 1.30797853]
[[ 0.73697623  0.59100905  0.32798528]
 [ 0.59100905 -0.32798528 -0.73697623]
 [ 0.32798528 -0.73697623  0.59100905]]


In [3]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
lambda1 = eigVals[0]
print(lambda1)

6.0489173395223075


In [6]:
mul = lambda1 * i
print(mul)

[[6.04891734 0.         0.        ]
 [0.         6.04891734 0.        ]
 [0.         0.         6.04891734]]


In [7]:
sub = A - mul
print(sub)

[[-2.04891734  2.          1.        ]
 [ 2.         -3.04891734  1.        ]
 [ 1.          1.         -4.04891734]]


In [9]:
det = np.linalg.det(sub)
print(det)

-4.4952012551417033e-14


In [10]:
print(np.isclose(det, 0))

True


## So property satisfied