# Matrices :

In [1]:
import numpy as np

In [6]:
A = np.array(([1, 2], [3, 4]))

B = np.array(([5, 6], [7, 8]))

In [8]:
shape1 = A.shape
dim1 = A.ndim
shape2 = B.shape
dim2 = B.ndim

In [10]:
print("Shape : ")
print(shape1)
print(shape2)

Shape : 
(2, 2)
(2, 2)


In [12]:
print("Dimensions : ")
print(dim1)
print(dim2)

Dimensions : 
2
2


In [13]:
transpose1 = A.T
transpose2 = B.T

print("Transpose : ")
print(transpose1)
print(transpose2)

Transpose : 
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [14]:
det1 = np.linalg.det(A)
det2 = np.linalg.det(B)

print("Determinant : ")
print(det1)
print(det2)

Determinant : 
-2.0000000000000004
-2.000000000000005


In [15]:
inv1 = np.linalg.inv(A)
inv2 = np.linalg.inv(B)

print("Inverse : ")
print(inv1)
print(inv2)

Inverse : 
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]


In [17]:
addition = A + B
subtraction = A - B
multiplication = np.dot(A, B)
mul = A * B

print(addition)
print(subtraction)
print(multiplication)
print(mul)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [18]:
block1 = np.array(([2, 1], [3, 4]))
block2 = np.array(([5, 6], [7, 8]))

blk = np.block([
    [block1, np.zeros((2, 3), dtype=int)],
    [np.zeros((1, 2), dtype=int),np.array([[9]]), np.zeros((1, 2), dtype=int)],
    [np.zeros((2, 3), dtype=int), block2]
])

print(blk)

[[2 1 0 0 0]
 [3 4 0 0 0]
 [0 0 9 0 0]
 [0 0 0 5 6]
 [0 0 0 7 8]]


In [19]:
det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [20]:
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
m = np.dot(A, inverse)
print(m)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [34]:
iden = np.eye(5)
print(iden)
zero = np.zeros((5, 5))
print(zero)
one = np.ones((5, 5))
print(one)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
mat = iden + blk
print(mat)

[[ 3.  1.  0.  0.  0.]
 [ 3.  5.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  6.  6.]
 [ 0.  0.  0.  7.  9.]]
