In [2]:
import numpy as np

In [4]:
A = np.array(([1, 2], [3, 4]))
determinant = np.linalg.det(A)
determinant

np.float64(-2.0000000000000004)

In [5]:
inverse = np.linalg.inv(A)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Properties of Matrix Multiplication Verification :

### 1. AB is not equal to BA

In [6]:
A = np.array(([1, 2], [3, 4]))
B = np.array(([5, 6], [7, 8]))
AB = np.dot(A, B)
BA = np.dot(B, A)

In [7]:
print(AB)

[[19 22]
 [43 50]]


In [8]:
print(BA)

[[23 34]
 [31 46]]


### 3. Associative property (AB)C = A(BC)

In [11]:
C = np.array(([9, 10], [11, 12]))
AB = np.dot(A, B)
BC = np.dot(B, C)
lhs = np.dot(AB, C)
rhs = np.dot(A, BC)

In [12]:
print(lhs)

[[ 413  454]
 [ 937 1030]]


In [13]:
print(rhs)

[[ 413  454]
 [ 937 1030]]


### 3. Distributive Property A(B+C) = AB + AC

In [14]:
b_plus_c = B + C
lhs = np.dot(A, b_plus_c)
AC = np.dot(A, C)
rhs = AB + AC

In [15]:
lhs

array([[ 50,  56],
       [114, 128]])

In [16]:
rhs

array([[ 50,  56],
       [114, 128]])